
// *** GENERATED BY COMMON/GENERATEHEADERS.PY ***
// Class file to store common communication information 
package com.example.bluetoothrgbled_android;
// ** BEGIN CONSTANT DEFINITIONS **
public class GeneratedConstants {
	// ** BEGIN INSTRUCTION DEFINITIONS **
	// Instruction pair: led_color
	public final static byte INST_SET_LED = (byte) 0b10001000;
	public final static byte INST_CNF_LED = (byte) 0b00001000;
	// Instruction pair: add_float
	public final static byte INST_ADD_FL = (byte) 0b10000001;
	public final static byte INST_ADD_FL_RESP = (byte) 0b00000001;
	// Instruction pair: stop_all
	public final static byte INST_STOP_ALL = (byte) 0b11111110;
	public final static byte INST_STPD_ALL = (byte) 0b01111110;

	// Other value: stop_all
	public final static byte START_BYTE = (byte) 0b00000000;

	// Other value: stop_all
	public final static int MESSAGE_LENGTH = (int) 6;

}
