 // *** GENERATED BY COMMON/GENERATEHEADERS.PY ***
// Header file to store common communication information
#include <Arduino.h>
#ifndef GLOBAL_HEADER
#define GLOBAL_HEADER
// ** BEGIN INSTRUCTION DEFINITIONS **
typedef enum {
	// Instruction pair: conn_conf
	INST_CONN_REQ = 0b11000000,
	INST_CONN_CONF = 0b01000000,
	// Instruction pair: led_color
	INST_SET_LED = 0b10001000,
	INST_CNF_LED = 0b00001000,
	// Instruction pair: ping_float
	INST_PING_FLO = 0b10000001,
	INST_PONG_FLO = 0b00000001,
	// Instruction pair: ping_int
	INST_PING_INT = 0b10000010,
	INST_PONG_INT = 0b00000010,
	// Instruction pair: stop_all
	INST_STOP_ALL = 0b11111110,
	INST_STPD_ALL = 0b01111110
} instr_code;

#define START_BYTE 0b00000000
#define MESSAGE_LENGTH 6

#endif
